     */NLAMBA / NLAMBA
     */FAULTV / FAULTV
     */ERREXP / ERREXP
     */ERRORN / ERRORN
     */MCONS / MCONS
     */MEVAL / MEVAL
     */ZNIL / ZNIL
     */DCLV / DCLV
C
C
      COMMON
     */ LISTT / LISTT
     */ BASEFT / BASEFT
     */ COMMAT / COMMAT
     */ NLAMBD / NLAMBD
     */ ATOMT / ATOMT
     */ NNAMBD / NNAMBD
     */ NAPPID / NAPPID
     */ REDEFT / REDEFT
     */ CXTT / CXTT
     */ COMPT /COMPT
     */ ARRAYT / ARRAYT
     */ STR / STR   
     */ TUPLE / TUPLE
     */ CLASS / CLASS
     */ BAG / BAG
     */ LNUM / LNUM
     */ SNUM / SNUM
C
C
      COMMON
     */ ALMODE / ALMODE
     */ FLAG / FLAG
     */BUFLAG /BUFLAG
     */ UNNO / UNNO
     */ NTYPEE / NTYPEE
     */ ATOMT1 / ATOMT1
     */ NATOML / NATOML
     */ UNNO2 / UNNO2
     */ RUNO / RUNO
C
      COMMON
     */ NREDMO / NREDMO
     */ STRC / STRC
     */ COMMAM / COMMAM
     */ BASEFM / BASEFM
C
      COMMON
     */ CXT / D1(3),CXT(256)
     */ KEY / D2(3),KEY(256)
     */ R / F1(3),R(128)
     */ F2(3),S(128)
     */ CXTX / F3(3), CXTX(128)
     */ PADRE / F4(3),PADRE(128)
     */ FIRSTS / F5(3),FIRSTS (128)