        SUBROUTINE MPATTF
C
        IMPLICIT INTEGER(A-Z)
C
C
        INTEGER*2
        * FTYPE,DUE,
        *NREDMO,PILA
        *RRADIX,CXT,KEY,RADIX,KEYM,KEY1,KEY2,TRE,R1,REDEFT,
        * UNO,DUMMY,KEYTEM,NENTPO,CXTT,SNUM,NAPPID,ACXT,
        * AAK,LIB,LIST,R,S,CXTX,PADRE,FIRSTS,FIRSTB
C
        LOGICAL FLAG
C
         COMMON /I1/t10 /LIFE/LIFE (128)
         COMMON /VALUE/ FWQ(4) ,VALUE(1023)
         COMMON / KGBC / KGBC
         COMMON /LISTA/PILA (256) /NREDMO/NREDMO
         COMMON /CONTAP/CONTAP /LASTAP/LASTAP /SCTSON/SCTSON /LISTSC/LISTSC
        */SCTHEA/SCTHEA /LISPXA/LISPXA /ERRORA/ERRORA
         COMMON /REDEFT/REDEFT
         LOGICAL LOOKA P
         COMMON
        */ UNIT / UNIT
C
         COMMON
        */ ABLOCK / V1(3),ABLOCK(1284)
        */ BBLOCK / V2(3),BBLOCK(3072)
        */ CBLOCK / V3(3),CBLOCK(4096)
        */ FLA / FLA
        */ FLB / FLB
        */ FLC / FLC
        */ NAPPOI / NAPPOI
        */ BPOINT / BPOINT
        */ CPOINT / CPOINT
        */ SNUM / SNUM
C
         COMMON
        */ CPLIST / BBC(3) ,CPLIST ( 128)
        */ CAR / B1(4) ,CAR(15767)
        */ CDR / B2(4) ,CDR(15767)
        */ ALMODE / ALMODE
        */ NENTPO / NENTPO
C
         COMMON
        */ R / C1(3) ,R(128)
        */ S / C2(3) ,S(128)
        */ PADRE / C3(3),PADRE(128)
        */ FIRSTS / C4(3),FIRSTS(128)
        */ FIRSTB / C5(3),FIRSTB(128)
        */ LIST / C6(3),LIST(128)
        */ LIB / LIB
        */ CXTX / B1(3),CXTX(128)
        */ CXT / BB1(3),CXT(256)
        */ KEY / BB2(3),KEY(256)
